In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Determine the risk determine the level risk for each cluster for each cluster in model for 2021 and 2022

## Clustergin model 2021

In [ ]:
"""
Load dataframe
"""
GMM_2021 = pd.read_csv("df_clustered_GMM.csv",delimiter="~", encoding = 'latin1' )
GMM_2021.head()

In [5]:
"""
Groupby Cluter and delete columns that aren't risk factors
"""
Risk_score_2021 = GMM_2021.groupby("Cluster").mean().reset_index()
Risk_score_2021 = Risk_score_2021.drop(["cod_barrio","cod_mpio","cod_dpto","sexo_persona","edad_c","cod_vereda"],axis=1)

In [6]:
"""
calculate percentage for each risk factor
"""

df_pct = Risk_score_2021/Risk_score_2021[Risk_score_2021.columns].sum()
df_pct["Cluster"] = round(df_pct["Cluster"]*10)

In [7]:
"""
calculate weighted for each risk factor
"""
df_pct["risk_weight"] = round(df_pct.mean(axis=1),2)

In [9]:
"""
Stablish conditions foe each risk level
"""
conditionlist = [
    (df_pct['risk_weight'] == 0.46 ) ,
    (df_pct['risk_weight'] == 0.35 ),
    (df_pct['risk_weight'] == 0.24 ),
    (df_pct['risk_weight'] == 0.20 ),
    (df_pct['risk_weight'] == 0.12) ]
choicelist = ['High', 'High-Mid', 'Mid', 'Mid-Low', 'Low']

In [10]:
"""
Create risk level in dataframe
"""
df_pct["risk_level"] = np.select(conditionlist, choicelist, default='Not Specified')

In [11]:
"""
Rename variable
"""
summary_risk_level_sisben_2021 = df_pct 
summary_risk_level_sisben_2021

In [13]:
"""
Export final dataframe with main characteristics and risk level
"""
summary_risk_level_sisben_2021.to_csv("summary_risk_level_sisben_2021.csv", sep="~", index=False, encoding = "latin1")

## Clustering model 2022

Please, consider the previous instructions for determine the risk level for 2022 clustering. the method is the same.

In [14]:
GMM_2022 = pd.read_csv("df_clustered_GMM_2022.csv",delimiter="~", encoding = 'latin1' )
GMM_2022.head()

,Cod_barrio,NOM_BARRIO,uso_vivienda,tip_vivienda,tip_mat_pisos,ind_tiene_energia,ind_tiene_alcantarillado,ind_tiene_gas,ind_tiene_recoleccion,ind_tiene_acueducto,...,I9,I10,I11,I12,I13,I14,I15,Nivel,C,Cluster
0,0,BARRIO_S4,10441,12368,30359,10596,19954,17850,15251,20459,...,2104,303,7511,4038,1016,266,1918,47766.0,43820.4,3
1,1,EL PAULON VILLA PATRICIA,421,560,1235,436,607,540,485,568,...,69,5,147,186,59,52,152,1705.0,1697.1,0
2,2,EL PAULON VILLA LINA,965,1326,2973,988,1355,1371,1095,1302,...,151,26,337,390,143,320,435,3972.0,4113.0,0
3,3,COLORADOS,2846,4038,6870,2854,3000,3205,2912,3116,...,462,92,270,154,36,32,824,14257.0,8922.6,5
4,4,EL PAULON,1133,1349,3173,1142,1577,1479,1207,1294,...,166,45,161,444,47,85,363,4815.0,4515.0,2

In [20]:
Risk_score_2022 = GMM_2022.groupby("Cluster").mean().reset_index()
Risk_score_2022 = Risk_score_2022.drop("Cod_barrio",axis=1)
Risk_score_2022

,Cluster,uso_vivienda,tip_vivienda,tip_mat_pisos,ind_tiene_energia,ind_tiene_alcantarillado,ind_tiene_gas,ind_tiene_recoleccion,ind_tiene_acueducto,tip_origen_agua,...,I8,I9,I10,I11,I12,I13,I14,I15,Nivel,C
0,0,668.037975,972.645570,1708.759494,682.898734,873.531646,938.481013,715.962025,920.177215,1961.405063,...,480.101266,139.620253,23.632911,252.139241,205.493671,27.620253,59.405063,209.556962,3354.746835,2557.067089
1,1,4401.866667,6604.066667,10440.666667,4412.133333,4532.733333,4827.333333,4459.066667,4561.933333,5251.333333,...,3174.866667,827.866667,131.666667,160.066667,130.866667,29.733333,51.933333,1274.600000,23496.466667,14604.920000
2,2,1213.684211,1824.605263,2872.000000,1220.526316,1344.947368,1377.421053,1243.000000,1393.052632,2121.947368,...,865.131579,236.815789,37.815789,179.368421,131.263158,14.368421,22.131579,331.605263,6679.789474,4161.386842
3,3,10441.000000,12368.000000,30359.000000,10596.000000,19954.000000,17850.000000,15251.000000,20459.000000,52856.000000,...,6698.000000,2104.000000,303.000000,7511.000000,4038.000000,1016.000000,266.000000,1918.000000,47766.000000,43820.400000
4,4,116.614815,178.992593,282.007407,117.540741,131.207407,138.451852,120.659259,134.274074,211.903704,...,79.229630,27.644444,3.207407,17.659259,14.592593,2.800000,5.125926,37.355556,598.874074,410.103333
5,5,2331.700000,3278.050000,5803.950000,2374.450000,2632.550000,2868.900000,2431.850000,2734.150000,4441.600000,...,1707.250000,427.450000,85.550000,402.450000,300.850000,69.400000,150.250000,745.250000,12019.400000,8363.632500

In [27]:
df_pct_22 = Risk_score_2022/Risk_score_2022[Risk_score_2022.columns].sum()
df_pct_22["Cluster"] = round(df_pct_22["Cluster"]*100/7)
df_pct_22

,Cluster,uso_vivienda,tip_vivienda,tip_mat_pisos,ind_tiene_energia,ind_tiene_alcantarillado,ind_tiene_gas,ind_tiene_recoleccion,ind_tiene_acueducto,tip_origen_agua,...,I8,I9,I10,I11,I12,I13,I14,I15,Nivel,C
0,0.0,0.034843,0.038557,0.033201,0.035195,0.029642,0.033516,0.029559,0.030467,0.029343,...,0.036918,0.037100,0.040407,0.029584,0.042624,0.023812,0.107066,0.046399,0.035721,0.034594
1,1.0,0.229588,0.261792,0.202864,0.227388,0.153814,0.172401,0.184095,0.151044,0.078561,...,0.244135,0.219979,0.225120,0.018781,0.027145,0.025634,0.093600,0.282218,0.250188,0.197584
2,2.0,0.063302,0.072329,0.055803,0.062902,0.045639,0.049193,0.051318,0.046124,0.031745,...,0.066525,0.062926,0.064656,0.021046,0.027227,0.012387,0.039888,0.073423,0.071126,0.056298
3,3.0,0.544571,0.490281,0.589880,0.546086,0.677119,0.637487,0.629646,0.677392,0.790734,...,0.515049,0.559069,0.518061,0.881295,0.837574,0.875921,0.479412,0.424678,0.508607,0.592828
4,4.0,0.006082,0.007095,0.005479,0.006058,0.004452,0.004945,0.004981,0.004446,0.003170,...,0.006092,0.007346,0.005484,0.002072,0.003027,0.002414,0.009238,0.008271,0.006377,0.005548
5,5.0,0.121614,0.129945,0.112772,0.122372,0.089333,0.102459,0.100400,0.090527,0.066447,...,0.131281,0.113581,0.146271,0.047221,0.062403,0.059832,0.270796,0.165011,0.127981,0.113148

In [30]:
df_pct_22["risk_weight"] = round(df_pct_22.mean(axis=1),2)
df_pct_22

,Cluster,uso_vivienda,tip_vivienda,tip_mat_pisos,ind_tiene_energia,ind_tiene_alcantarillado,ind_tiene_gas,ind_tiene_recoleccion,ind_tiene_acueducto,tip_origen_agua,...,I9,I10,I11,I12,I13,I14,I15,Nivel,C,risk_weight
0,0.0,0.034843,0.038557,0.033201,0.035195,0.029642,0.033516,0.029559,0.030467,0.029343,...,0.037100,0.040407,0.029584,0.042624,0.023812,0.107066,0.046399,0.035721,0.034594,0.04
1,1.0,0.229588,0.261792,0.202864,0.227388,0.153814,0.172401,0.184095,0.151044,0.078561,...,0.219979,0.225120,0.018781,0.027145,0.025634,0.093600,0.282218,0.250188,0.197584,0.22
2,2.0,0.063302,0.072329,0.055803,0.062902,0.045639,0.049193,0.051318,0.046124,0.031745,...,0.062926,0.064656,0.021046,0.027227,0.012387,0.039888,0.073423,0.071126,0.056298,0.09
3,3.0,0.544571,0.490281,0.589880,0.546086,0.677119,0.637487,0.629646,0.677392,0.790734,...,0.559069,0.518061,0.881295,0.837574,0.875921,0.479412,0.424678,0.508607,0.592828,0.61
4,4.0,0.006082,0.007095,0.005479,0.006058,0.004452,0.004945,0.004981,0.004446,0.003170,...,0.007346,0.005484,0.002072,0.003027,0.002414,0.009238,0.008271,0.006377,0.005548,0.08
5,5.0,0.121614,0.129945,0.112772,0.122372,0.089333,0.102459,0.100400,0.090527,0.066447,...,0.113581,0.146271,0.047221,0.062403,0.059832,0.270796,0.165011,0.127981,0.113148,0.21

In [41]:
conditionlist_2022 = [
    (df_pct_22['risk_weight'] == 0.61 ),
    (df_pct_22['risk_weight'] == 0.22 ),
    (df_pct_22['risk_weight'] == 0.21 ),
    (df_pct_22['risk_weight'] == 0.09 ),
    (df_pct_22['risk_weight'] == 0.08), 
    (df_pct_22['risk_weight'] == 0.04)]
choicelist_2022 = ['Very-High', 'High', 'High-Mid', 'Mid', 'Mid-Low', 'Low']

In [43]:
df_pct_22["risk_level"] = np.select(conditionlist_2022, choicelist_2022, default='Not Specified')
df_pct_22

,Cluster,uso_vivienda,tip_vivienda,tip_mat_pisos,ind_tiene_energia,ind_tiene_alcantarillado,ind_tiene_gas,ind_tiene_recoleccion,ind_tiene_acueducto,tip_origen_agua,...,I10,I11,I12,I13,I14,I15,Nivel,C,risk_weight,risk_level
0,0.0,0.034843,0.038557,0.033201,0.035195,0.029642,0.033516,0.029559,0.030467,0.029343,...,0.040407,0.029584,0.042624,0.023812,0.107066,0.046399,0.035721,0.034594,0.04,Low
1,1.0,0.229588,0.261792,0.202864,0.227388,0.153814,0.172401,0.184095,0.151044,0.078561,...,0.225120,0.018781,0.027145,0.025634,0.093600,0.282218,0.250188,0.197584,0.22,High
2,2.0,0.063302,0.072329,0.055803,0.062902,0.045639,0.049193,0.051318,0.046124,0.031745,...,0.064656,0.021046,0.027227,0.012387,0.039888,0.073423,0.071126,0.056298,0.09,Mid
3,3.0,0.544571,0.490281,0.589880,0.546086,0.677119,0.637487,0.629646,0.677392,0.790734,...,0.518061,0.881295,0.837574,0.875921,0.479412,0.424678,0.508607,0.592828,0.61,Very-High
4,4.0,0.006082,0.007095,0.005479,0.006058,0.004452,0.004945,0.004981,0.004446,0.003170,...,0.005484,0.002072,0.003027,0.002414,0.009238,0.008271,0.006377,0.005548,0.08,Mid-Low
5,5.0,0.121614,0.129945,0.112772,0.122372,0.089333,0.102459,0.100400,0.090527,0.066447,...,0.146271,0.047221,0.062403,0.059832,0.270796,0.165011,0.127981,0.113148,0.21,High-Mid

In [44]:
summary_risk_level_sisben_2022 = df_pct_22

In [45]:
summary_risk_level_sisben_2022

,Cluster,uso_vivienda,tip_vivienda,tip_mat_pisos,ind_tiene_energia,ind_tiene_alcantarillado,ind_tiene_gas,ind_tiene_recoleccion,ind_tiene_acueducto,tip_origen_agua,...,I10,I11,I12,I13,I14,I15,Nivel,C,risk_weight,risk_level
0,0.0,0.034843,0.038557,0.033201,0.035195,0.029642,0.033516,0.029559,0.030467,0.029343,...,0.040407,0.029584,0.042624,0.023812,0.107066,0.046399,0.035721,0.034594,0.04,Low
1,1.0,0.229588,0.261792,0.202864,0.227388,0.153814,0.172401,0.184095,0.151044,0.078561,...,0.225120,0.018781,0.027145,0.025634,0.093600,0.282218,0.250188,0.197584,0.22,High
2,2.0,0.063302,0.072329,0.055803,0.062902,0.045639,0.049193,0.051318,0.046124,0.031745,...,0.064656,0.021046,0.027227,0.012387,0.039888,0.073423,0.071126,0.056298,0.09,Mid
3,3.0,0.544571,0.490281,0.589880,0.546086,0.677119,0.637487,0.629646,0.677392,0.790734,...,0.518061,0.881295,0.837574,0.875921,0.479412,0.424678,0.508607,0.592828,0.61,Very-High
4,4.0,0.006082,0.007095,0.005479,0.006058,0.004452,0.004945,0.004981,0.004446,0.003170,...,0.005484,0.002072,0.003027,0.002414,0.009238,0.008271,0.006377,0.005548,0.08,Mid-Low
5,5.0,0.121614,0.129945,0.112772,0.122372,0.089333,0.102459,0.100400,0.090527,0.066447,...,0.146271,0.047221,0.062403,0.059832,0.270796,0.165011,0.127981,0.113148,0.21,High-Mid

In [46]:
summary_risk_level_sisben_2022.to_csv("summary_risk_level_sisben_2022.csv", sep="~", index=False, encoding = "latin1")